syntax = "proto3";
import "scroller.proto";

enum SettingValueTypes {
    User = 0;
    Chat = 1;
    Command = 2;
    Button = 3;
    Ranks = 4;
}

message SettingsScrollerData {
    ScrollerData data = 1;
    SettingValueTypes type = 2; // valueType
}

message SettingShowData {
    SettingValueTypes type = 1; // valueType
    uint32 settingId = 2; // setting's id
    uint64 userId = 3; // user's id
    uint32 page = 4; // back page index
}

message SettingBackButtonData {
    uint64 id = 1; // user's id
}

message SettingSetButtonData {
    uint64 id = 1; // user's id
    uint32 settingId = 2; // setting's id
    SettingValueTypes type = 3; // setting's valueType
    uint32 value = 4; // new setting's value index
}