export const MILLISECONDS_IN_SECOND = 1000
export const SECONDS_IN_MINUTE = 60
export const MINUTES_IN_HOUR = 60
export const HOURS_IN_DAY = 24

export const DAYS_IN_WEEK = 7
export const DAYS_IN_MONTH = 30
export const DAYS_IN_YEAR = 365

export const MILLISECONDS_IN_MINUTE = MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE
export const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * MINUTES_IN_HOUR
export const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * HOURS_IN_DAY

export const MILLISECONDS_IN_WEEK = MILLISECONDS_IN_DAY * DAYS_IN_WEEK
export const MILLISECONDS_IN_MONTH = MILLISECONDS_IN_DAY * DAYS_IN_MONTH
export const MILLISECONDS_IN_YEAR = MILLISECONDS_IN_DAY * DAYS_IN_YEAR

export const MAX_CONVERSATION_TIME = 5 * MILLISECONDS_IN_MINUTE
export const COIN_DROP_TIME = 2750
export const CUBE_DROP_TIME = 3500
export const SUMMON_DELAY = 1500

export const CHAT_MEMBER_CACHE_TIME = MILLISECONDS_IN_MINUTE * 3
export const IDEA_VOTE_TIME = MILLISECONDS_IN_WEEK
export const NEWBIE_TIME = MILLISECONDS_IN_SECOND * 15

export const DEFAULT_WORK_COOLDOWN = MILLISECONDS_IN_HOUR * 3
export const CATALOG_WORK_COOLDOWN = MILLISECONDS_IN_HOUR
export const SAVE_COOLDOWN = 10 * MILLISECONDS_IN_MINUTE
export const COOKIE_TIME = 10 * MILLISECONDS_IN_MINUTE