// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file chat.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat.proto.
 */
export const file_chat: GenFile = /*@__PURE__*/
  fileDesc("CgpjaGF0LnByb3RvIhgKFlRvZ2dsZVB1YmxpY0J1dHRvbkRhdGFiBnByb3RvMw");

/**
 * @generated from message TogglePublicButtonData
 */
export type TogglePublicButtonData = Message<"TogglePublicButtonData"> & {
};

/**
 * Describes the message TogglePublicButtonData.
 * Use `create(TogglePublicButtonDataSchema)` to create a new message.
 */
export const TogglePublicButtonDataSchema: GenMessage<TogglePublicButtonData> = /*@__PURE__*/
  messageDesc(file_chat, 0);

