// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file commands.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file commands.proto.
 */
export const file_commands: GenFile = /*@__PURE__*/
  fileDesc("Cg5jb21tYW5kcy5wcm90byJPChRDb21tYW5kc1Njcm9sbGVyRGF0YRIbCgRkYXRhGAEgASgLMg0uU2Nyb2xsZXJEYXRhEhoKBHR5cGUYAiABKA4yDC5Db21tYW5kVHlwZSosCgtDb21tYW5kVHlwZRIICgRUZXh0EAASCQoFUGhvdG8QARIICgREaWNlEAJiBnByb3RvMw", [file_scroller]);

/**
 * @generated from message CommandsScrollerData
 */
export type CommandsScrollerData = Message<"CommandsScrollerData"> & {
  /**
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;

  /**
   * @generated from field: CommandType type = 2;
   */
  type: CommandType;
};

/**
 * Describes the message CommandsScrollerData.
 * Use `create(CommandsScrollerDataSchema)` to create a new message.
 */
export const CommandsScrollerDataSchema: GenMessage<CommandsScrollerData> = /*@__PURE__*/
  messageDesc(file_commands, 0);

/**
 * @generated from enum CommandType
 */
export enum CommandType {
  /**
   * @generated from enum value: Text = 0;
   */
  Text = 0,

  /**
   * @generated from enum value: Photo = 1;
   */
  Photo = 1,

  /**
   * @generated from enum value: Dice = 2;
   */
  Dice = 2,
}

/**
 * Describes the enum CommandType.
 */
export const CommandTypeSchema: GenEnum<CommandType> = /*@__PURE__*/
  enumDesc(file_commands, 0);

