// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file cubes.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cubes.proto.
 */
export const file_cubes: GenFile = /*@__PURE__*/
  fileDesc("CgtjdWJlcy5wcm90byJSChNDdWJlU3RhcnRCdXR0b25EYXRhEg0KBWZpcnN0GAEgASgEEg4KBnNlY29uZBgCIAEoBBIPCgdpc0FncmVlGAMgASgIEgsKA2JldBgEIAEoDWIGcHJvdG8z");

/**
 * @generated from message CubeStartButtonData
 */
export type CubeStartButtonData = Message<"CubeStartButtonData"> & {
  /**
   * @generated from field: uint64 first = 1;
   */
  first: bigint;

  /**
   * @generated from field: uint64 second = 2;
   */
  second: bigint;

  /**
   * @generated from field: bool isAgree = 3;
   */
  isAgree: boolean;

  /**
   * @generated from field: uint32 bet = 4;
   */
  bet: number;
};

/**
 * Describes the message CubeStartButtonData.
 * Use `create(CubeStartButtonDataSchema)` to create a new message.
 */
export const CubeStartButtonDataSchema: GenMessage<CubeStartButtonData> = /*@__PURE__*/
  messageDesc(file_cubes, 0);

