// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file dev.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file dev.proto.
 */
export const file_dev: GenFile = /*@__PURE__*/
  fileDesc("CglkZXYucHJvdG8iLQoDRGV2EgoKAmlkGAEgASgNEhEKBG5hbWUYAiABKAlIAIgBAUIHCgVfbmFtZWIGcHJvdG8z");

/**
 * @generated from message Dev
 */
export type Dev = Message<"Dev"> & {
  /**
   * user's id
   *
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * any string
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;
};

/**
 * Describes the message Dev.
 * Use `create(DevSchema)` to create a new message.
 */
export const DevSchema: GenMessage<Dev> = /*@__PURE__*/
  messageDesc(file_dev, 0);

