// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file duels.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file duels.proto.
 */
export const file_duels: GenFile = /*@__PURE__*/
  fileDesc("CgtkdWVscy5wcm90byotCgtTa2lsbEF0dGFjaxIICgRGYWlsEAASCgoGTm9ybWFsEAESCAoEQ3JpdBACYgZwcm90bzM");

/**
 * @generated from enum SkillAttack
 */
export enum SkillAttack {
  /**
   * @generated from enum value: Fail = 0;
   */
  Fail = 0,

  /**
   * @generated from enum value: Normal = 1;
   */
  Normal = 1,

  /**
   * @generated from enum value: Crit = 2;
   */
  Crit = 2,
}

/**
 * Describes the enum SkillAttack.
 */
export const SkillAttackSchema: GenEnum<SkillAttack> = /*@__PURE__*/
  enumDesc(file_duels, 0);

