// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file export-import.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file export-import.proto.
 */
export const file_export_import: GenFile = /*@__PURE__*/
  fileDesc("ChNleHBvcnQtaW1wb3J0LnByb3RvIj0KHkV4cG9ydEltcG9ydFNjcm9sbGVyQnV0dG9uRGF0YRIbCgRkYXRhGAEgASgLMg0uU2Nyb2xsZXJEYXRhIjQKEEV4cG9ydEJ1dHRvbkRhdGESCgoCaWQYASABKAQSFAoMZGVmaW5pdGlvbklkGAIgASgNIjQKEEltcG9ydEJ1dHRvbkRhdGESCgoCaWQYASABKAQSFAoMZGVmaW5pdGlvbklkGAIgASgNIkwKGkV4cG9ydEltcG9ydFNob3dCdXR0b25EYXRhEgoKAmlkGAEgASgEEhQKDGRlZmluaXRpb25JZBgCIAEoDRIMCgRwYWdlGAMgASgNYgZwcm90bzM", [file_scroller]);

/**
 * @generated from message ExportImportScrollerButtonData
 */
export type ExportImportScrollerButtonData = Message<"ExportImportScrollerButtonData"> & {
  /**
   * scroller's data
   *
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message ExportImportScrollerButtonData.
 * Use `create(ExportImportScrollerButtonDataSchema)` to create a new message.
 */
export const ExportImportScrollerButtonDataSchema: GenMessage<ExportImportScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_export_import, 0);

/**
 * @generated from message ExportButtonData
 */
export type ExportButtonData = Message<"ExportButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * export import definition's id
   *
   * @generated from field: uint32 definitionId = 2;
   */
  definitionId: number;
};

/**
 * Describes the message ExportButtonData.
 * Use `create(ExportButtonDataSchema)` to create a new message.
 */
export const ExportButtonDataSchema: GenMessage<ExportButtonData> = /*@__PURE__*/
  messageDesc(file_export_import, 1);

/**
 * @generated from message ImportButtonData
 */
export type ImportButtonData = Message<"ImportButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * export import definition's id
   *
   * @generated from field: uint32 definitionId = 2;
   */
  definitionId: number;
};

/**
 * Describes the message ImportButtonData.
 * Use `create(ImportButtonDataSchema)` to create a new message.
 */
export const ImportButtonDataSchema: GenMessage<ImportButtonData> = /*@__PURE__*/
  messageDesc(file_export_import, 2);

/**
 * @generated from message ExportImportShowButtonData
 */
export type ExportImportShowButtonData = Message<"ExportImportShowButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * export import definition's id
   *
   * @generated from field: uint32 definitionId = 2;
   */
  definitionId: number;

  /**
   * back page's index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message ExportImportShowButtonData.
 * Use `create(ExportImportShowButtonDataSchema)` to create a new message.
 */
export const ExportImportShowButtonDataSchema: GenMessage<ExportImportShowButtonData> = /*@__PURE__*/
  messageDesc(file_export_import, 3);

