// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file faq.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file faq.proto.
 */
export const file_faq: GenFile = /*@__PURE__*/
  fileDesc("CglmYXEucHJvdG8iNAoVRmFxU2Nyb2xsZXJCdXR0b25EYXRhEhsKBGRhdGEYASABKAsyDS5TY3JvbGxlckRhdGEiLAoNRmFxQnV0dG9uRGF0YRINCgVpbmRleBgCIAEoDRIMCgRwYWdlGAMgASgNYgZwcm90bzM", [file_scroller]);

/**
 * @generated from message FaqScrollerButtonData
 */
export type FaqScrollerButtonData = Message<"FaqScrollerButtonData"> & {
  /**
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message FaqScrollerButtonData.
 * Use `create(FaqScrollerButtonDataSchema)` to create a new message.
 */
export const FaqScrollerButtonDataSchema: GenMessage<FaqScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_faq, 0);

/**
 * @generated from message FaqButtonData
 */
export type FaqButtonData = Message<"FaqButtonData"> & {
  /**
   * faq's index
   *
   * @generated from field: uint32 index = 2;
   */
  index: number;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message FaqButtonData.
 * Use `create(FaqButtonDataSchema)` to create a new message.
 */
export const FaqButtonDataSchema: GenMessage<FaqButtonData> = /*@__PURE__*/
  messageDesc(file_faq, 1);

