// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file gun.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file gun.proto.
 */
export const file_gun: GenFile = /*@__PURE__*/
  fileDesc("CglndW4ucHJvdG8iLgoQR3VuU2V0QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIOCgZpdGVtSWQYAiABKA1iBnByb3RvMw");

/**
 * @generated from message GunSetButtonData
 */
export type GunSetButtonData = Message<"GunSetButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * items's id
   *
   * @generated from field: uint32 itemId = 2;
   */
  itemId: number;
};

/**
 * Describes the message GunSetButtonData.
 * Use `create(GunSetButtonDataSchema)` to create a new message.
 */
export const GunSetButtonDataSchema: GenMessage<GunSetButtonData> = /*@__PURE__*/
  messageDesc(file_gun, 0);

