// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file ideas.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ideas.proto.
 */
export const file_ideas: GenFile = /*@__PURE__*/
  fileDesc("CgtpZGVhcy5wcm90byIwChJJZGVhVm90ZUJ1dHRvbkRhdGESCgoCaWQYASABKA0SDgoGaXNDb29sGAIgASgIIj4KFElkZWFEZWxldGVCdXR0b25EYXRhEgoKAmlkGAEgASgNEhEKBHBhZ2UYAiABKA1IAIgBAUIHCgVfcGFnZWIGcHJvdG8z");

/**
 * @generated from message IdeaVoteButtonData
 */
export type IdeaVoteButtonData = Message<"IdeaVoteButtonData"> & {
  /**
   * idea's id
   *
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * like or dislike
   *
   * @generated from field: bool isCool = 2;
   */
  isCool: boolean;
};

/**
 * Describes the message IdeaVoteButtonData.
 * Use `create(IdeaVoteButtonDataSchema)` to create a new message.
 */
export const IdeaVoteButtonDataSchema: GenMessage<IdeaVoteButtonData> = /*@__PURE__*/
  messageDesc(file_ideas, 0);

/**
 * @generated from message IdeaDeleteButtonData
 */
export type IdeaDeleteButtonData = Message<"IdeaDeleteButtonData"> & {
  /**
   * idea's id
   *
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: optional uint32 page = 2;
   */
  page?: number | undefined;
};

/**
 * Describes the message IdeaDeleteButtonData.
 * Use `create(IdeaDeleteButtonDataSchema)` to create a new message.
 */
export const IdeaDeleteButtonDataSchema: GenMessage<IdeaDeleteButtonData> = /*@__PURE__*/
  messageDesc(file_ideas, 1);

