// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file inventory.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file inventory.proto.
 */
export const file_inventory: GenFile = /*@__PURE__*/
  fileDesc("Cg9pbnZlbnRvcnkucHJvdG8iOgobSW52ZW50b3J5U2Nyb2xsZXJCdXR0b25EYXRhEhsKBGRhdGEYASABKAsyDS5TY3JvbGxlckRhdGEiQwoXSW52ZW50b3J5U2hvd0J1dHRvbkRhdGESCgoCaWQYASABKAQSDgoGaXRlbUlkGAIgASgNEgwKBHBhZ2UYAyABKA0iQwoXSW52ZW50b3J5R2lmdEJ1dHRvbkRhdGESCgoCaWQYASABKAQSDgoGaXRlbUlkGAIgASgNEgwKBHBhZ2UYAyABKA0iNAoWSW52ZW50b3J5VXNlQnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIOCgZpdGVtSWQYAiABKA1iBnByb3RvMw", [file_scroller]);

/**
 * @generated from message InventoryScrollerButtonData
 */
export type InventoryScrollerButtonData = Message<"InventoryScrollerButtonData"> & {
  /**
   * scroller's data
   *
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message InventoryScrollerButtonData.
 * Use `create(InventoryScrollerButtonDataSchema)` to create a new message.
 */
export const InventoryScrollerButtonDataSchema: GenMessage<InventoryScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_inventory, 0);

/**
 * @generated from message InventoryShowButtonData
 */
export type InventoryShowButtonData = Message<"InventoryShowButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * item's id
   *
   * @generated from field: uint32 itemId = 2;
   */
  itemId: number;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message InventoryShowButtonData.
 * Use `create(InventoryShowButtonDataSchema)` to create a new message.
 */
export const InventoryShowButtonDataSchema: GenMessage<InventoryShowButtonData> = /*@__PURE__*/
  messageDesc(file_inventory, 1);

/**
 * @generated from message InventoryGiftButtonData
 */
export type InventoryGiftButtonData = Message<"InventoryGiftButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * item's id
   *
   * @generated from field: uint32 itemId = 2;
   */
  itemId: number;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message InventoryGiftButtonData.
 * Use `create(InventoryGiftButtonDataSchema)` to create a new message.
 */
export const InventoryGiftButtonDataSchema: GenMessage<InventoryGiftButtonData> = /*@__PURE__*/
  messageDesc(file_inventory, 2);

/**
 * @generated from message InventoryUseButtonData
 */
export type InventoryUseButtonData = Message<"InventoryUseButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * item's id
   *
   * @generated from field: uint32 itemId = 2;
   */
  itemId: number;
};

/**
 * Describes the message InventoryUseButtonData.
 * Use `create(InventoryUseButtonDataSchema)` to create a new message.
 */
export const InventoryUseButtonDataSchema: GenMessage<InventoryUseButtonData> = /*@__PURE__*/
  messageDesc(file_inventory, 3);

