// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file link.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file link.proto.
 */
export const file_link: GenFile = /*@__PURE__*/
  fileDesc("CgpsaW5rLnByb3RvIjUKFkxpbmtTY3JvbGxlckJ1dHRvbkRhdGESGwoEZGF0YRgBIAEoCzINLlNjcm9sbGVyRGF0YSIrCg5MaW5rQnV0dG9uRGF0YRIKCgJpZBgBIAEoBBINCgVpbmRleBgCIAEoDWIGcHJvdG8z", [file_scroller]);

/**
 * @generated from message LinkScrollerButtonData
 */
export type LinkScrollerButtonData = Message<"LinkScrollerButtonData"> & {
  /**
   * scroller's data
   *
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message LinkScrollerButtonData.
 * Use `create(LinkScrollerButtonDataSchema)` to create a new message.
 */
export const LinkScrollerButtonDataSchema: GenMessage<LinkScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_link, 0);

/**
 * @generated from message LinkButtonData
 */
export type LinkButtonData = Message<"LinkButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * linkedChats' index
   *
   * @generated from field: uint32 index = 2;
   */
  index: number;
};

/**
 * Describes the message LinkButtonData.
 * Use `create(LinkButtonDataSchema)` to create a new message.
 */
export const LinkButtonDataSchema: GenMessage<LinkButtonData> = /*@__PURE__*/
  messageDesc(file_link, 1);

