// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file marriage.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file marriage.proto.
 */
export const file_marriage: GenFile = /*@__PURE__*/
  fileDesc("Cg5tYXJyaWFnZS5wcm90byJGCg9NYXJyeUJ1dHRvbkRhdGESEQoJc3VnZ2VzdGVyGAEgASgEEg4KBnRhcmdldBgCIAEoBBIQCghpc0FjY2VwdBgDIAEoCGIGcHJvdG8z");

/**
 * @generated from message MarryButtonData
 */
export type MarryButtonData = Message<"MarryButtonData"> & {
  /**
   * first partner id
   *
   * @generated from field: uint64 suggester = 1;
   */
  suggester: bigint;

  /**
   * second partner id
   *
   * @generated from field: uint64 target = 2;
   */
  target: bigint;

  /**
   * is accept 
   *
   * @generated from field: bool isAccept = 3;
   */
  isAccept: boolean;
};

/**
 * Describes the message MarryButtonData.
 * Use `create(MarryButtonDataSchema)` to create a new message.
 */
export const MarryButtonDataSchema: GenMessage<MarryButtonData> = /*@__PURE__*/
  messageDesc(file_marriage, 0);

