// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file new-chat-member.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file new-chat-member.proto.
 */
export const file_new_chat_member: GenFile = /*@__PURE__*/
  fileDesc("ChVuZXctY2hhdC1tZW1iZXIucHJvdG8iIAoSSm9pbkNoYXRCdXR0b25EYXRhEgoKAmlkGAEgASgEYgZwcm90bzM");

/**
 * @generated from message JoinChatButtonData
 */
export type JoinChatButtonData = Message<"JoinChatButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message JoinChatButtonData.
 * Use `create(JoinChatButtonDataSchema)` to create a new message.
 */
export const JoinChatButtonDataSchema: GenMessage<JoinChatButtonData> = /*@__PURE__*/
  messageDesc(file_new_chat_member, 0);

