// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file payment.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file payment.proto.
 */
export const file_payment: GenFile = /*@__PURE__*/
  fileDesc("Cg1wYXltZW50LnByb3RvIiMKEURvbmF0ZVBheW1lbnREYXRhEg4KBmNoYXRJZBgBIAEoA2IGcHJvdG8z");

/**
 * @generated from message DonatePaymentData
 */
export type DonatePaymentData = Message<"DonatePaymentData"> & {
  /**
   * chat id
   *
   * @generated from field: int64 chatId = 1;
   */
  chatId: bigint;
};

/**
 * Describes the message DonatePaymentData.
 * Use `create(DonatePaymentDataSchema)` to create a new message.
 */
export const DonatePaymentDataSchema: GenMessage<DonatePaymentData> = /*@__PURE__*/
  messageDesc(file_payment, 0);

