// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file proto.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto.proto.
 */
export const file_proto: GenFile = /*@__PURE__*/
  fileDesc("Cgtwcm90by5wcm90byIRCg9FbXB0eUJ1dHRvbkRhdGFiBnByb3RvMw");

/**
 * empty button data
 *
 * @generated from message EmptyButtonData
 */
export type EmptyButtonData = Message<"EmptyButtonData"> & {
};

/**
 * Describes the message EmptyButtonData.
 * Use `create(EmptyButtonDataSchema)` to create a new message.
 */
export const EmptyButtonDataSchema: GenMessage<EmptyButtonData> = /*@__PURE__*/
  messageDesc(file_proto, 0);

