// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file rp.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rp.proto.
 */
export const file_rp: GenFile = /*@__PURE__*/
  fileDesc("CghycC5wcm90byJHChpSb2xlcGxheVNjcm9sbGVyQnV0dG9uRGF0YRIgCgRkYXRhGAEgASgLMg0uU2Nyb2xsZXJEYXRhSACIAQFCBwoFX2RhdGEibwocUm9sZXBsYXlDaGFuZ2VDYXNlQnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIjCgljYXNlVmFsdWUYAiABKA4yEC5HcmFtbWF0aWNhbENhc2USEAoIb2JqZWN0SWQYAyABKAwSDAoEcGFnZRgEIAEoDSI6ChpSb2xlcGxheUVkaXRUZXh0QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIQCghvYmplY3RJZBgCIAEoDCIjChVSb2xlcGxheUFkZEJ1dHRvbkRhdGESCgoCaWQYASABKAQiRAoWUm9sZXBsYXlTaG93QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIQCghvYmplY3RJZBgCIAEoDBIMCgRwYWdlGAMgASgNIkYKGFJvbGVwbGF5RGVsZXRlQnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIQCghvYmplY3RJZBgCIAEoDBIMCgRwYWdlGAMgASgNKjkKD0dyYW1tYXRpY2FsQ2FzZRIMCghHZW5pdGl2ZRAAEgoKBkRhdGl2ZRABEgwKCENyZWF0aXZlEAJiBnByb3RvMw", [file_scroller]);

/**
 * @generated from message RoleplayScrollerButtonData
 */
export type RoleplayScrollerButtonData = Message<"RoleplayScrollerButtonData"> & {
  /**
   * scroller data
   *
   * @generated from field: optional ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message RoleplayScrollerButtonData.
 * Use `create(RoleplayScrollerButtonDataSchema)` to create a new message.
 */
export const RoleplayScrollerButtonDataSchema: GenMessage<RoleplayScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 0);

/**
 * @generated from message RoleplayChangeCaseButtonData
 */
export type RoleplayChangeCaseButtonData = Message<"RoleplayChangeCaseButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * grammatical case
   *
   * @generated from field: GrammaticalCase caseValue = 2;
   */
  caseValue: GrammaticalCase;

  /**
   * roleplay's objectId
   *
   * @generated from field: bytes objectId = 3;
   */
  objectId: Uint8Array;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 4;
   */
  page: number;
};

/**
 * Describes the message RoleplayChangeCaseButtonData.
 * Use `create(RoleplayChangeCaseButtonDataSchema)` to create a new message.
 */
export const RoleplayChangeCaseButtonDataSchema: GenMessage<RoleplayChangeCaseButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 1);

/**
 * @generated from message RoleplayEditTextButtonData
 */
export type RoleplayEditTextButtonData = Message<"RoleplayEditTextButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * roleplay's objectId
   *
   * @generated from field: bytes objectId = 2;
   */
  objectId: Uint8Array;
};

/**
 * Describes the message RoleplayEditTextButtonData.
 * Use `create(RoleplayEditTextButtonDataSchema)` to create a new message.
 */
export const RoleplayEditTextButtonDataSchema: GenMessage<RoleplayEditTextButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 2);

/**
 * @generated from message RoleplayAddButtonData
 */
export type RoleplayAddButtonData = Message<"RoleplayAddButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message RoleplayAddButtonData.
 * Use `create(RoleplayAddButtonDataSchema)` to create a new message.
 */
export const RoleplayAddButtonDataSchema: GenMessage<RoleplayAddButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 3);

/**
 * @generated from message RoleplayShowButtonData
 */
export type RoleplayShowButtonData = Message<"RoleplayShowButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * roleplay's objectId
   *
   * @generated from field: bytes objectId = 2;
   */
  objectId: Uint8Array;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message RoleplayShowButtonData.
 * Use `create(RoleplayShowButtonDataSchema)` to create a new message.
 */
export const RoleplayShowButtonDataSchema: GenMessage<RoleplayShowButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 4);

/**
 * @generated from message RoleplayDeleteButtonData
 */
export type RoleplayDeleteButtonData = Message<"RoleplayDeleteButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * roleplay's objectId
   *
   * @generated from field: bytes objectId = 2;
   */
  objectId: Uint8Array;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message RoleplayDeleteButtonData.
 * Use `create(RoleplayDeleteButtonDataSchema)` to create a new message.
 */
export const RoleplayDeleteButtonDataSchema: GenMessage<RoleplayDeleteButtonData> = /*@__PURE__*/
  messageDesc(file_rp, 5);

/**
 * @generated from enum GrammaticalCase
 */
export enum GrammaticalCase {
  /**
   * genitive case
   *
   * @generated from enum value: Genitive = 0;
   */
  Genitive = 0,

  /**
   * dative case
   *
   * @generated from enum value: Dative = 1;
   */
  Dative = 1,

  /**
   * instrumental case
   *
   * @generated from enum value: Creative = 2;
   */
  Creative = 2,
}

/**
 * Describes the enum GrammaticalCase.
 */
export const GrammaticalCaseSchema: GenEnum<GrammaticalCase> = /*@__PURE__*/
  enumDesc(file_rp, 0);

