// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file rule.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rule.proto.
 */
export const file_rule: GenFile = /*@__PURE__*/
  fileDesc("CgpydWxlLnByb3RvIjUKFlJ1bGVTY3JvbGxlckJ1dHRvbkRhdGESGwoEZGF0YRgBIAEoCzINLlNjcm9sbGVyRGF0YSIyChRSdWxlRGVsZXRlQnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIOCgZydWxlSWQYAiABKA0iNAoWUnVsZUVkaXRUZXh0QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBIOCgZydWxlSWQYAiABKA0iHwoRUnVsZUFkZEJ1dHRvbkRhdGESCgoCaWQYASABKARiBnByb3RvMw", [file_scroller]);

/**
 * @generated from message RuleScrollerButtonData
 */
export type RuleScrollerButtonData = Message<"RuleScrollerButtonData"> & {
  /**
   * scroller's data
   *
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message RuleScrollerButtonData.
 * Use `create(RuleScrollerButtonDataSchema)` to create a new message.
 */
export const RuleScrollerButtonDataSchema: GenMessage<RuleScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_rule, 0);

/**
 * @generated from message RuleDeleteButtonData
 */
export type RuleDeleteButtonData = Message<"RuleDeleteButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * rule's id
   *
   * @generated from field: uint32 ruleId = 2;
   */
  ruleId: number;
};

/**
 * Describes the message RuleDeleteButtonData.
 * Use `create(RuleDeleteButtonDataSchema)` to create a new message.
 */
export const RuleDeleteButtonDataSchema: GenMessage<RuleDeleteButtonData> = /*@__PURE__*/
  messageDesc(file_rule, 1);

/**
 * @generated from message RuleEditTextButtonData
 */
export type RuleEditTextButtonData = Message<"RuleEditTextButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * rule's id
   *
   * @generated from field: uint32 ruleId = 2;
   */
  ruleId: number;
};

/**
 * Describes the message RuleEditTextButtonData.
 * Use `create(RuleEditTextButtonDataSchema)` to create a new message.
 */
export const RuleEditTextButtonDataSchema: GenMessage<RuleEditTextButtonData> = /*@__PURE__*/
  messageDesc(file_rule, 2);

/**
 * @generated from message RuleAddButtonData
 */
export type RuleAddButtonData = Message<"RuleAddButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message RuleAddButtonData.
 * Use `create(RuleAddButtonDataSchema)` to create a new message.
 */
export const RuleAddButtonDataSchema: GenMessage<RuleAddButtonData> = /*@__PURE__*/
  messageDesc(file_rule, 3);

