// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file settings.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file settings.proto.
 */
export const file_settings: GenFile = /*@__PURE__*/
  fileDesc("Cg5zZXR0aW5ncy5wcm90byJhChRTZXR0aW5nc1Njcm9sbGVyRGF0YRIbCgRkYXRhGAEgASgLMg0uU2Nyb2xsZXJEYXRhEgoKAmlkGAIgASgDEiAKBHR5cGUYAyABKA4yEi5TZXR0aW5nVmFsdWVUeXBlcyJiCg9TZXR0aW5nU2hvd0RhdGESIAoEdHlwZRgBIAEoDjISLlNldHRpbmdWYWx1ZVR5cGVzEhEKCXNldHRpbmdJZBgCIAEoDRIKCgJpZBgDIAEoAxIOCgZ1c2VySWQYBCABKAQqSwoRU2V0dGluZ1ZhbHVlVHlwZXMSCAoEVXNlchAAEggKBENoYXQQARILCgdDb21tYW5kEAISCgoGQnV0dG9uEAMSCQoFUmFua3MQBGIGcHJvdG8z", [file_scroller]);

/**
 * @generated from message SettingsScrollerData
 */
export type SettingsScrollerData = Message<"SettingsScrollerData"> & {
  /**
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;

  /**
   * setting owner's id
   *
   * @generated from field: int64 id = 2;
   */
  id: bigint;

  /**
   * @generated from field: SettingValueTypes type = 3;
   */
  type: SettingValueTypes;
};

/**
 * Describes the message SettingsScrollerData.
 * Use `create(SettingsScrollerDataSchema)` to create a new message.
 */
export const SettingsScrollerDataSchema: GenMessage<SettingsScrollerData> = /*@__PURE__*/
  messageDesc(file_settings, 0);

/**
 * @generated from message SettingShowData
 */
export type SettingShowData = Message<"SettingShowData"> & {
  /**
   * @generated from field: SettingValueTypes type = 1;
   */
  type: SettingValueTypes;

  /**
   * setting's id
   *
   * @generated from field: uint32 settingId = 2;
   */
  settingId: number;

  /**
   * setting owner's id
   *
   * @generated from field: int64 id = 3;
   */
  id: bigint;

  /**
   * user's id
   *
   * @generated from field: uint64 userId = 4;
   */
  userId: bigint;
};

/**
 * Describes the message SettingShowData.
 * Use `create(SettingShowDataSchema)` to create a new message.
 */
export const SettingShowDataSchema: GenMessage<SettingShowData> = /*@__PURE__*/
  messageDesc(file_settings, 1);

/**
 * @generated from enum SettingValueTypes
 */
export enum SettingValueTypes {
  /**
   * @generated from enum value: User = 0;
   */
  User = 0,

  /**
   * @generated from enum value: Chat = 1;
   */
  Chat = 1,

  /**
   * @generated from enum value: Command = 2;
   */
  Command = 2,

  /**
   * @generated from enum value: Button = 3;
   */
  Button = 3,

  /**
   * @generated from enum value: Ranks = 4;
   */
  Ranks = 4,
}

/**
 * Describes the enum SettingValueTypes.
 */
export const SettingValueTypesSchema: GenEnum<SettingValueTypes> = /*@__PURE__*/
  enumDesc(file_settings, 0);

