// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file settings.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file settings.proto.
 */
export const file_settings: GenFile = /*@__PURE__*/
  fileDesc("Cg5zZXR0aW5ncy5wcm90byJVChRTZXR0aW5nc1Njcm9sbGVyRGF0YRIbCgRkYXRhGAEgASgLMg0uU2Nyb2xsZXJEYXRhEiAKBHR5cGUYAiABKA4yEi5TZXR0aW5nVmFsdWVUeXBlcyJkCg9TZXR0aW5nU2hvd0RhdGESIAoEdHlwZRgBIAEoDjISLlNldHRpbmdWYWx1ZVR5cGVzEhEKCXNldHRpbmdJZBgCIAEoDRIOCgZ1c2VySWQYAyABKAQSDAoEcGFnZRgEIAEoDSIjChVTZXR0aW5nQmFja0J1dHRvbkRhdGESCgoCaWQYASABKAQiZgoUU2V0dGluZ1NldEJ1dHRvbkRhdGESCgoCaWQYASABKAQSEQoJc2V0dGluZ0lkGAIgASgNEiAKBHR5cGUYAyABKA4yEi5TZXR0aW5nVmFsdWVUeXBlcxINCgV2YWx1ZRgEIAEoDSpLChFTZXR0aW5nVmFsdWVUeXBlcxIICgRVc2VyEAASCAoEQ2hhdBABEgsKB0NvbW1hbmQQAhIKCgZCdXR0b24QAxIJCgVSYW5rcxAEYgZwcm90bzM", [file_scroller]);

/**
 * @generated from message SettingsScrollerData
 */
export type SettingsScrollerData = Message<"SettingsScrollerData"> & {
  /**
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;

  /**
   * valueType
   *
   * @generated from field: SettingValueTypes type = 2;
   */
  type: SettingValueTypes;
};

/**
 * Describes the message SettingsScrollerData.
 * Use `create(SettingsScrollerDataSchema)` to create a new message.
 */
export const SettingsScrollerDataSchema: GenMessage<SettingsScrollerData> = /*@__PURE__*/
  messageDesc(file_settings, 0);

/**
 * @generated from message SettingShowData
 */
export type SettingShowData = Message<"SettingShowData"> & {
  /**
   * valueType
   *
   * @generated from field: SettingValueTypes type = 1;
   */
  type: SettingValueTypes;

  /**
   * setting's id
   *
   * @generated from field: uint32 settingId = 2;
   */
  settingId: number;

  /**
   * user's id
   *
   * @generated from field: uint64 userId = 3;
   */
  userId: bigint;

  /**
   * back page index
   *
   * @generated from field: uint32 page = 4;
   */
  page: number;
};

/**
 * Describes the message SettingShowData.
 * Use `create(SettingShowDataSchema)` to create a new message.
 */
export const SettingShowDataSchema: GenMessage<SettingShowData> = /*@__PURE__*/
  messageDesc(file_settings, 1);

/**
 * @generated from message SettingBackButtonData
 */
export type SettingBackButtonData = Message<"SettingBackButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message SettingBackButtonData.
 * Use `create(SettingBackButtonDataSchema)` to create a new message.
 */
export const SettingBackButtonDataSchema: GenMessage<SettingBackButtonData> = /*@__PURE__*/
  messageDesc(file_settings, 2);

/**
 * @generated from message SettingSetButtonData
 */
export type SettingSetButtonData = Message<"SettingSetButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * setting's id
   *
   * @generated from field: uint32 settingId = 2;
   */
  settingId: number;

  /**
   * setting's valueType
   *
   * @generated from field: SettingValueTypes type = 3;
   */
  type: SettingValueTypes;

  /**
   * new setting's value index
   *
   * @generated from field: uint32 value = 4;
   */
  value: number;
};

/**
 * Describes the message SettingSetButtonData.
 * Use `create(SettingSetButtonDataSchema)` to create a new message.
 */
export const SettingSetButtonDataSchema: GenMessage<SettingSetButtonData> = /*@__PURE__*/
  messageDesc(file_settings, 3);

/**
 * @generated from enum SettingValueTypes
 */
export enum SettingValueTypes {
  /**
   * @generated from enum value: User = 0;
   */
  User = 0,

  /**
   * @generated from enum value: Chat = 1;
   */
  Chat = 1,

  /**
   * @generated from enum value: Command = 2;
   */
  Command = 2,

  /**
   * @generated from enum value: Button = 3;
   */
  Button = 3,

  /**
   * @generated from enum value: Ranks = 4;
   */
  Ranks = 4,
}

/**
 * Describes the enum SettingValueTypes.
 */
export const SettingValueTypesSchema: GenEnum<SettingValueTypes> = /*@__PURE__*/
  enumDesc(file_settings, 0);

