// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file shop.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file shop.proto.
 */
export const file_shop: GenFile = /*@__PURE__*/
  fileDesc("CgpzaG9wLnByb3RvIkwKElNob3BTaG93QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBINCgVpbmRleBgCIAEoDRIMCgRwYWdlGAMgASgNEg0KBWNvdW50GAQgASgNIksKEVNob3BCdXlCdXR0b25EYXRhEgoKAmlkGAEgASgEEg0KBWluZGV4GAIgASgNEgwKBHBhZ2UYAyABKA0SDQoFY291bnQYBCABKA0iPgoTU2hvcENvdW50QnV0dG9uRGF0YRIKCgJpZBgBIAEoBBINCgVpbmRleBgCIAEoDRIMCgRwYWdlGAMgASgNYgZwcm90bzM");

/**
 * @generated from message ShopShowButtonData
 */
export type ShopShowButtonData = Message<"ShopShowButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * shopItems' index
   *
   * @generated from field: uint32 index = 2;
   */
  index: number;

  /**
   * back page
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;

  /**
   * item's count
   *
   * @generated from field: uint32 count = 4;
   */
  count: number;
};

/**
 * Describes the message ShopShowButtonData.
 * Use `create(ShopShowButtonDataSchema)` to create a new message.
 */
export const ShopShowButtonDataSchema: GenMessage<ShopShowButtonData> = /*@__PURE__*/
  messageDesc(file_shop, 0);

/**
 * @generated from message ShopBuyButtonData
 */
export type ShopBuyButtonData = Message<"ShopBuyButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * shopItems' index
   *
   * @generated from field: uint32 index = 2;
   */
  index: number;

  /**
   * back page
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;

  /**
   * item's count
   *
   * @generated from field: uint32 count = 4;
   */
  count: number;
};

/**
 * Describes the message ShopBuyButtonData.
 * Use `create(ShopBuyButtonDataSchema)` to create a new message.
 */
export const ShopBuyButtonDataSchema: GenMessage<ShopBuyButtonData> = /*@__PURE__*/
  messageDesc(file_shop, 1);

/**
 * @generated from message ShopCountButtonData
 */
export type ShopCountButtonData = Message<"ShopCountButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * shopItems' index
   *
   * @generated from field: uint32 index = 2;
   */
  index: number;

  /**
   * back page
   *
   * @generated from field: uint32 page = 3;
   */
  page: number;
};

/**
 * Describes the message ShopCountButtonData.
 * Use `create(ShopCountButtonDataSchema)` to create a new message.
 */
export const ShopCountButtonDataSchema: GenMessage<ShopCountButtonData> = /*@__PURE__*/
  messageDesc(file_shop, 2);

