// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file short-command.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ScrollerData } from "./scroller_pb";
import { file_scroller } from "./scroller_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file short-command.proto.
 */
export const file_short_command: GenFile = /*@__PURE__*/
  fileDesc("ChNzaG9ydC1jb21tYW5kLnByb3RvIjsKHFNob3J0Q29tbWFuZERlbGV0ZUJ1dHRvbkRhdGESCgoCaWQYASABKAQSDwoHY29tbWFuZBgCIAEoDCI9Ch5TaG9ydENvbW1hbmRTY3JvbGxlckJ1dHRvbkRhdGESGwoEZGF0YRgBIAEoCzINLlNjcm9sbGVyRGF0YWIGcHJvdG8z", [file_scroller]);

/**
 * @generated from message ShortCommandDeleteButtonData
 */
export type ShortCommandDeleteButtonData = Message<"ShortCommandDeleteButtonData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * short command's objectId
   *
   * @generated from field: bytes command = 2;
   */
  command: Uint8Array;
};

/**
 * Describes the message ShortCommandDeleteButtonData.
 * Use `create(ShortCommandDeleteButtonDataSchema)` to create a new message.
 */
export const ShortCommandDeleteButtonDataSchema: GenMessage<ShortCommandDeleteButtonData> = /*@__PURE__*/
  messageDesc(file_short_command, 0);

/**
 * @generated from message ShortCommandScrollerButtonData
 */
export type ShortCommandScrollerButtonData = Message<"ShortCommandScrollerButtonData"> & {
  /**
   * scroller's data
   *
   * @generated from field: ScrollerData data = 1;
   */
  data?: ScrollerData | undefined;
};

/**
 * Describes the message ShortCommandScrollerButtonData.
 * Use `create(ShortCommandScrollerButtonDataSchema)` to create a new message.
 */
export const ShortCommandScrollerButtonDataSchema: GenMessage<ShortCommandScrollerButtonData> = /*@__PURE__*/
  messageDesc(file_short_command, 1);

