// @generated by protoc-gen-es v2.15.0 with parameter "target=ts"
// @generated from file user.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvIiUKCUNsYXNzRGF0YRIKCgJpZBgBIAEoBBIMCgR0eXBlGAIgASgJYgZwcm90bzM");

/**
 * @generated from message ClassData
 */
export type ClassData = Message<"ClassData"> & {
  /**
   * user's id
   *
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * class' type
   *
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message ClassData.
 * Use `create(ClassDataSchema)` to create a new message.
 */
export const ClassDataSchema: GenMessage<ClassData> = /*@__PURE__*/
  messageDesc(file_user, 0);

